# Keep the two same-subnet LUCID camera interfaces separated at ARP level.
net.ipv4.conf.all.arp_filter = 1
net.ipv4.conf.default.arp_filter = 1
net.ipv4.conf.enx08beac363cc9.arp_filter = 1
net.ipv4.conf.enx08beac363cce.arp_filter = 1
net.ipv4.conf.all.arp_ignore = 1
net.ipv4.conf.default.arp_ignore = 1
net.ipv4.conf.enx08beac363cc9.arp_ignore = 1
net.ipv4.conf.enx08beac363cce.arp_ignore = 1
net.ipv4.conf.all.arp_announce = 2
net.ipv4.conf.default.arp_announce = 2
net.ipv4.conf.enx08beac363cc9.arp_announce = 2
net.ipv4.conf.enx08beac363cce.arp_announce = 2
